#!/bin/bash
# Created By Janda Baper Group

if [[ $USER != 'root' ]]; then
	echo "Masuk user root dulu boss !!!"
	exit
fi
while :
do
	clear
	echo " "
	echo " "
	echo "-----------------------------------------"
	echo "       Menghapus Firewall IPtables       "
	echo "-----------------------------------------"
	echo -e "\e[031;1m 1\e[0m) Menghapus INPUT Firewall (\e[34;1medit-port-openssh\e[0m)"
	echo -e "\e[031;1m 2\e[0m) Menghapus FORWARD Firewall (\e[34;1medit-port-dropbear\e[0m)"
	echo -e "\e[031;1m 3\e[0m) Menghapus OUTPUT Firewall (\e[34;1medit-port-squid\e[0m)"
	echo -e "\e[031;1m 4\e[0m) Menghapus semua Firewall (\e[34;1medit-port-openvpn\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) Exit"
	echo ""
	read -p "Pilih salah satu (1-4 or x): " option2
	case $option2 in
		1)
		clear
		sudo iptables -F INPUT
		exit
		;;
		2)
		clear
		sudo iptables -F FORWARD
		exit
		;;
		3)
		clear
		sudo iptables -F OUTPUT
		exit
		;;
		4)
		clear
		sudo iptables -F
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done
cd
