#!/bin/bash

#created by Dominic Kabel
#https://github.com/domkab16

# Shared under GNU v3
# Mod By Janda Bper GGroup

clear

	#Cek user root
	if [ "$EUID" -ne "0" ]
	then
		echo "Login root dulu Boss"
		exit
	fi

	#Choose External Port
	echo "Masukan port yang mau di open"
	read -r "extport"

	#Find vpn address
	echo "Masukan IP VPS yang ingin Anda port forward"
	read "vpnip"

	#Find Internal port
	echo "Masukan port internal"
	read "intport"

	#What protocol

	echo "Masukan protocol tcp / udp / tcp/udp"
	read protocol
	if [ \( "$protocol" == "tcp" \) -o \( "$protocol" == "udp" \) -o \( "$protocol" == "tcp/udp" \) ]
	then
		echo "Selesai"
	else
		echo "Maaf, anda harus menetukan protocol !!!"
		exit
	fi

	#Periksa kembali dengan pengguna apakah ini konfigurasi yang benar
	echo "Apakah konfigurasi ini sudah benar ?"
	echo "$vpnip:$intport dengan $protocol $extport sebagai port external? [y/n]"
	read "konfirmasi"

	#Execution
	if [ "$konfirmasi" == "y" ]
	then

		if [ "$protocol" == "tcp" ]
		then
			iptables -A PREROUTING -t nat -i  ens4 -p tcp --dport "$extport" -j DNAT --to "$vpnip":"$intport"
			iptables -A FORWARD -p tcp -d "$vpnip" --dport "$extport" -j ACCEPT
		fi

		if [ "$protocol" == "udp" ]
		then
			iptables -A PREROUTING -t nat -i ens4 -p udp --dport "$extport" -j DNAT --to "$vpnip":"$intport"
			iptables -A FORWARD -p udp -d "$vpnip" --dport "$extport" -j ACCEPT
		fi

		if [ "$protocol" == "tcp/udp" ]
		then
			iptables -A PREROUTING -t nat -i  ens4 -p tcp --dport "$extport" -j DNAT --to "$vpnip":"$intport"
			iptables -A FORWARD -p tcp -d "$vpnip" --dport "$extport" -j ACCEPT
			iptables -A PREROUTING -t nat -i ens4 -p udp --dport "$extport" -j DNAT --to "$vpnip":"$intport"
			iptables -A FORWARD -p udp -d "$vpnip" --dport "$extport" -j ACCEPT
		fi

	else
		echo "Script Terminating"
		exit
	fi

	#Asking To Save rules
	echo "Apakah Anda ingin menyimpan aturan atau menghapusnya saat reboot? [y/n]"
	echo "Harap reboot sebelum menjalankan dan menyimpan skrip atau aturan iptables ini"
	read "simpan"

	if [ "$simpan" == "y" ]
	then
		echo "Menyimpan"
		iptables-save > /etc/iptables/rules.v4
	fi

	#Reminder to port foward server side
	echo "Selesai! Ingatlah untuk menambahkan aturan firewall untuk $extport $protocol sisi server"
	echo "Goodbye Jomblo!"
	echo "Mod By Janda Baper Group"
